name: Auto-Branch and Pull Request

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'  # Optionally ignore specific paths (like workflows)
      - 'LaTeX/**'
      - '**.fits'
      - '**.git**'
    types:
      - modified  # Only trigger on modified files
      - removed   # Only trigger on removed files
jobs:
  auto-create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Move Commits to a New Branch
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          BRANCH="auto-${GITHUB_ACTOR}-${TIMESTAMP}"
          git checkout -b $BRANCH
          git push origin $BRANCH
          echo "Created new branch: $BRANCH"
      
      - name: Create Pull Request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const timestamp = new Date().toISOString().replace(/[-:.]/g, "");
            const branchName = `auto-${context.actor}-${timestamp}`;
            await github.rest.pulls.create({
              owner,
              repo,
              title: `Auto PR from ${context.actor}`,
              head: branchName,
              base: "main",
              body: "This PR was auto-generated to move commits from main."
            });
      
