name: Auto-Branch and Pull Request

on:
  push:
    branches:
      - main
    paths:
      - '**'  # Monitor all files
    paths-ignore:
      - '.github/**'  # Optionally ignore specific paths (like workflows)
      - '.LaTeX/**'
    types:
      - modified  # Only trigger on modified files
      - removed   # Only trigger on removed files

jobs:
  auto-branch:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Create a new branch
      - name: Create a new branch
        id: create_branch
        run: |
          branch_name="auto-branch-$(date +%Y%m%d%H%M%S)"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b "$branch_name"
          git push origin "$branch_name"
          echo "branch_name=$branch_name" >> $GITHUB_ENV

      # Step 3: Create a pull request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.branch_name }}
          base: main
          title: "Auto PR: Changes from direct commit to master"
          body: |
            This pull request was automatically created because a direct commit was made to the `master` branch.
            Please review and merge this PR to incorporate the changes properly.

      
