name: Cleanup Merged Branches
on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Branch
        run: |
          BRANCH=$(jq -r '.pull_request.head.ref' $GITHUB_EVENT_PATH)
          if [[ $BRANCH == auto-* ]]; then
            git push origin --delete $BRANCH || echo "Branch already deleted."
          fi
