name: Set Assigned issue as in progress
on:
  issues:
    types: 
     - assigned
jobs:
  automate-project-labelling:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: "JAR:VIS"
          column: In Progress
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
