name: 'Ruff CI'
on:
  workflow_dispatch: 
  push:
  
jobs:
  build-tests:
    name: Pytest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11","3.12.3","3.12.8"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        cache: pip
        python-version: ${{ matrix.python-version }}
    
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install  ruff
        pip install -r python/requirements.txt
    - name: Run Linter (ruff)
      run: ruff check python/ --config .github/pyproject.toml  
