name: Add New Issue to Project
on:
  issues:
    types: 
     - opened
jobs:
  automate-project-labelling:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: "JAR:VIS"
          column: To Do
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
